/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionRouteRouteImport } from './routes/collection/route'
import { Route as DiscoverRouteRouteImport } from './routes/discover/route'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as NowPlayingRouteImport } from './routes/now-playing'
import { Route as PlaylistsRouteRouteImport } from './routes/playlists/route'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as CollectionIndexRouteImport } from './routes/collection/index'
import { Route as DiscoverIndexRouteImport } from './routes/discover/index'
import { Route as PlaylistsIndexRouteImport } from './routes/playlists/index'
import { Route as PlaylistsPlaylistIdRouteImport } from './routes/playlists/$playlistId'
import { Route as RadioIndexRouteImport } from './routes/radio/index'
import { Route as CollectionAlbumsAlbumIdRouteImport } from './routes/collection/albums/$albumId'
import { Route as CollectionArtistsArtistKeyRouteImport } from './routes/collection/artists/$artistKey'
import { Route as DiscoverReleasesReleaseIdRouteImport } from './routes/discover/releases/$releaseId'
import { Route as RadioSeriesSeriesIdRouteImport } from './routes/radio/series/$seriesId'
import { Route as RadioShowsShowIdRouteImport } from './routes/radio/shows/$showId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRouteRoute = CollectionRouteRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRouteRoute = DiscoverRouteRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const NowPlayingRoute = NowPlayingRouteImport.update({
  id: '/now-playing',
  path: '/now-playing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsRouteRoute = PlaylistsRouteRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIndexRoute = CollectionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionRouteRoute,
} as any)
const DiscoverIndexRoute = DiscoverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DiscoverRouteRoute,
} as any)
const PlaylistsIndexRoute = PlaylistsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlaylistsRouteRoute,
} as any)
const PlaylistsPlaylistIdRoute = PlaylistsPlaylistIdRouteImport.update({
  id: '/$playlistId',
  path: '/$playlistId',
  getParentRoute: () => PlaylistsRouteRoute,
} as any)
const RadioIndexRoute = RadioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RadioRoute,
} as any)
const CollectionAlbumsAlbumIdRoute = CollectionAlbumsAlbumIdRouteImport.update({
  id: '/albums/$albumId',
  path: '/albums/$albumId',
  getParentRoute: () => CollectionRouteRoute,
} as any)
const CollectionArtistsArtistKeyRoute =
  CollectionArtistsArtistKeyRouteImport.update({
    id: '/artists/$artistKey',
    path: '/artists/$artistKey',
    getParentRoute: () => CollectionRouteRoute,
  } as any)
const DiscoverReleasesReleaseIdRoute =
  DiscoverReleasesReleaseIdRouteImport.update({
    id: '/releases/$releaseId',
    path: '/releases/$releaseId',
    getParentRoute: () => DiscoverRouteRoute,
  } as any)
const RadioSeriesSeriesIdRoute = RadioSeriesSeriesIdRouteImport.update({
  id: '/series/$seriesId',
  path: '/series/$seriesId',
  getParentRoute: () => RadioRoute,
} as any)
const RadioShowsShowIdRoute = RadioShowsShowIdRouteImport.update({
  id: '/shows/$showId',
  path: '/shows/$showId',
  getParentRoute: () => RadioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRouteRouteWithChildren
  '/discover': typeof DiscoverRouteRouteWithChildren
  '/playlists': typeof PlaylistsRouteRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/now-playing': typeof NowPlayingRoute
  '/radio': typeof RadioRouteWithChildren
  '/recent': typeof RecentRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/collection/': typeof CollectionIndexRoute
  '/discover/': typeof DiscoverIndexRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/radio/': typeof RadioIndexRoute
  '/collection/albums/$albumId': typeof CollectionAlbumsAlbumIdRoute
  '/collection/artists/$artistKey': typeof CollectionArtistsArtistKeyRoute
  '/discover/releases/$releaseId': typeof DiscoverReleasesReleaseIdRoute
  '/radio/series/$seriesId': typeof RadioSeriesSeriesIdRoute
  '/radio/shows/$showId': typeof RadioShowsShowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/now-playing': typeof NowPlayingRoute
  '/recent': typeof RecentRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/collection': typeof CollectionIndexRoute
  '/discover': typeof DiscoverIndexRoute
  '/playlists': typeof PlaylistsIndexRoute
  '/radio': typeof RadioIndexRoute
  '/collection/albums/$albumId': typeof CollectionAlbumsAlbumIdRoute
  '/collection/artists/$artistKey': typeof CollectionArtistsArtistKeyRoute
  '/discover/releases/$releaseId': typeof DiscoverReleasesReleaseIdRoute
  '/radio/series/$seriesId': typeof RadioSeriesSeriesIdRoute
  '/radio/shows/$showId': typeof RadioShowsShowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collection': typeof CollectionRouteRouteWithChildren
  '/discover': typeof DiscoverRouteRouteWithChildren
  '/playlists': typeof PlaylistsRouteRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/now-playing': typeof NowPlayingRoute
  '/radio': typeof RadioRouteWithChildren
  '/recent': typeof RecentRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/collection/': typeof CollectionIndexRoute
  '/discover/': typeof DiscoverIndexRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/radio/': typeof RadioIndexRoute
  '/collection/albums/$albumId': typeof CollectionAlbumsAlbumIdRoute
  '/collection/artists/$artistKey': typeof CollectionArtistsArtistKeyRoute
  '/discover/releases/$releaseId': typeof DiscoverReleasesReleaseIdRoute
  '/radio/series/$seriesId': typeof RadioSeriesSeriesIdRoute
  '/radio/shows/$showId': typeof RadioShowsShowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collection'
    | '/discover'
    | '/playlists'
    | '/favorites'
    | '/now-playing'
    | '/radio'
    | '/recent'
    | '/playlists/$playlistId'
    | '/collection/'
    | '/discover/'
    | '/playlists/'
    | '/radio/'
    | '/collection/albums/$albumId'
    | '/collection/artists/$artistKey'
    | '/discover/releases/$releaseId'
    | '/radio/series/$seriesId'
    | '/radio/shows/$showId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/now-playing'
    | '/recent'
    | '/playlists/$playlistId'
    | '/collection'
    | '/discover'
    | '/playlists'
    | '/radio'
    | '/collection/albums/$albumId'
    | '/collection/artists/$artistKey'
    | '/discover/releases/$releaseId'
    | '/radio/series/$seriesId'
    | '/radio/shows/$showId'
  id:
    | '__root__'
    | '/'
    | '/collection'
    | '/discover'
    | '/playlists'
    | '/favorites'
    | '/now-playing'
    | '/radio'
    | '/recent'
    | '/playlists/$playlistId'
    | '/collection/'
    | '/discover/'
    | '/playlists/'
    | '/radio/'
    | '/collection/albums/$albumId'
    | '/collection/artists/$artistKey'
    | '/discover/releases/$releaseId'
    | '/radio/series/$seriesId'
    | '/radio/shows/$showId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionRouteRoute: typeof CollectionRouteRouteWithChildren
  DiscoverRouteRoute: typeof DiscoverRouteRouteWithChildren
  PlaylistsRouteRoute: typeof PlaylistsRouteRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  NowPlayingRoute: typeof NowPlayingRoute
  RadioRoute: typeof RadioRouteWithChildren
  RecentRoute: typeof RecentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/now-playing': {
      id: '/now-playing'
      path: '/now-playing'
      fullPath: '/now-playing'
      preLoaderRoute: typeof NowPlayingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/': {
      id: '/collection/'
      path: '/'
      fullPath: '/collection/'
      preLoaderRoute: typeof CollectionIndexRouteImport
      parentRoute: typeof CollectionRouteRoute
    }
    '/discover/': {
      id: '/discover/'
      path: '/'
      fullPath: '/discover/'
      preLoaderRoute: typeof DiscoverIndexRouteImport
      parentRoute: typeof DiscoverRouteRoute
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/'
      fullPath: '/playlists/'
      preLoaderRoute: typeof PlaylistsIndexRouteImport
      parentRoute: typeof PlaylistsRouteRoute
    }
    '/playlists/$playlistId': {
      id: '/playlists/$playlistId'
      path: '/$playlistId'
      fullPath: '/playlists/$playlistId'
      preLoaderRoute: typeof PlaylistsPlaylistIdRouteImport
      parentRoute: typeof PlaylistsRouteRoute
    }
    '/radio/': {
      id: '/radio/'
      path: '/'
      fullPath: '/radio/'
      preLoaderRoute: typeof RadioIndexRouteImport
      parentRoute: typeof RadioRoute
    }
    '/collection/albums/$albumId': {
      id: '/collection/albums/$albumId'
      path: '/albums/$albumId'
      fullPath: '/collection/albums/$albumId'
      preLoaderRoute: typeof CollectionAlbumsAlbumIdRouteImport
      parentRoute: typeof CollectionRouteRoute
    }
    '/collection/artists/$artistKey': {
      id: '/collection/artists/$artistKey'
      path: '/artists/$artistKey'
      fullPath: '/collection/artists/$artistKey'
      preLoaderRoute: typeof CollectionArtistsArtistKeyRouteImport
      parentRoute: typeof CollectionRouteRoute
    }
    '/discover/releases/$releaseId': {
      id: '/discover/releases/$releaseId'
      path: '/releases/$releaseId'
      fullPath: '/discover/releases/$releaseId'
      preLoaderRoute: typeof DiscoverReleasesReleaseIdRouteImport
      parentRoute: typeof DiscoverRouteRoute
    }
    '/radio/series/$seriesId': {
      id: '/radio/series/$seriesId'
      path: '/series/$seriesId'
      fullPath: '/radio/series/$seriesId'
      preLoaderRoute: typeof RadioSeriesSeriesIdRouteImport
      parentRoute: typeof RadioRoute
    }
    '/radio/shows/$showId': {
      id: '/radio/shows/$showId'
      path: '/shows/$showId'
      fullPath: '/radio/shows/$showId'
      preLoaderRoute: typeof RadioShowsShowIdRouteImport
      parentRoute: typeof RadioRoute
    }
  }
}

interface CollectionRouteRouteChildren {
  CollectionIndexRoute: typeof CollectionIndexRoute
  CollectionAlbumsAlbumIdRoute: typeof CollectionAlbumsAlbumIdRoute
  CollectionArtistsArtistKeyRoute: typeof CollectionArtistsArtistKeyRoute
}

const CollectionRouteRouteChildren: CollectionRouteRouteChildren = {
  CollectionIndexRoute: CollectionIndexRoute,
  CollectionAlbumsAlbumIdRoute: CollectionAlbumsAlbumIdRoute,
  CollectionArtistsArtistKeyRoute: CollectionArtistsArtistKeyRoute,
}

const CollectionRouteRouteWithChildren = CollectionRouteRoute._addFileChildren(
  CollectionRouteRouteChildren,
)

interface DiscoverRouteRouteChildren {
  DiscoverIndexRoute: typeof DiscoverIndexRoute
  DiscoverReleasesReleaseIdRoute: typeof DiscoverReleasesReleaseIdRoute
}

const DiscoverRouteRouteChildren: DiscoverRouteRouteChildren = {
  DiscoverIndexRoute: DiscoverIndexRoute,
  DiscoverReleasesReleaseIdRoute: DiscoverReleasesReleaseIdRoute,
}

const DiscoverRouteRouteWithChildren = DiscoverRouteRoute._addFileChildren(
  DiscoverRouteRouteChildren,
)

interface PlaylistsRouteRouteChildren {
  PlaylistsPlaylistIdRoute: typeof PlaylistsPlaylistIdRoute
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute
}

const PlaylistsRouteRouteChildren: PlaylistsRouteRouteChildren = {
  PlaylistsPlaylistIdRoute: PlaylistsPlaylistIdRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
}

const PlaylistsRouteRouteWithChildren = PlaylistsRouteRoute._addFileChildren(
  PlaylistsRouteRouteChildren,
)

interface RadioRouteChildren {
  RadioIndexRoute: typeof RadioIndexRoute
  RadioSeriesSeriesIdRoute: typeof RadioSeriesSeriesIdRoute
  RadioShowsShowIdRoute: typeof RadioShowsShowIdRoute
}

const RadioRouteChildren: RadioRouteChildren = {
  RadioIndexRoute: RadioIndexRoute,
  RadioSeriesSeriesIdRoute: RadioSeriesSeriesIdRoute,
  RadioShowsShowIdRoute: RadioShowsShowIdRoute,
}

const RadioRouteWithChildren = RadioRoute._addFileChildren(RadioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionRouteRoute: CollectionRouteRouteWithChildren,
  DiscoverRouteRoute: DiscoverRouteRouteWithChildren,
  PlaylistsRouteRoute: PlaylistsRouteRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  NowPlayingRoute: NowPlayingRoute,
  RadioRoute: RadioRouteWithChildren,
  RecentRoute: RecentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
